/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardSlide: typeof import('./components/css/cardSlide.vue')['default']
    CardSlideOld: typeof import('./components/css/cardSlide-old.vue')['default']
    copy: typeof import('./components/Welcome copy.vue')['default']
    Detail: typeof import('./components/Detail.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    GressSlideHover: typeof import('./components/css/gressSlideHover.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Primary: typeof import('./components/css/primary.vue')['default']
    RotateBall: typeof import('./components/css/rotateBall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrangeHeadPortrait: typeof import('./components/css/strangeHeadPortrait.vue')['default']
    ThreeDball: typeof import('./components/css/threeDball.vue')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
    WelcomeOld: typeof import('./components/Welcome-old.vue')['default']
  }
}
